#!/usr/bin/env bash
stopvnc -non-stop-dbus 2>/dev/null
export PULSE_SERVER=127.0.0.1
export DISPLAY=:233
TMOE_LOCALE_FILE=/usr/local/etc/tmoe-linux/locale.txt
TMOE_X11_PASSWD_FILE=${HOME}/.vnc/x11passwd
TMOE_X11_RESOLUTION=1440x720
TCP_PORT_FOR_RFB_PROTOCOL=5901
X11VNC_CURSOR_ARROW=2
TMOE_TOOL_DIR='/usr/local/etc/tmoe-linux/git/tools'
XSESSION_FILE='/etc/X11/xinit/Xsession'
#################
start_windows_10_pulse_audio_server() {
    . /usr/local/etc/tmoe-linux/git/tools/gui/wsl_pulse_audio
}
#####################
start_tmoe_x11vnc() {
    unset "${@}"
    set -- "${@}" "-ncache_cr"
    set -- "${@}" "-xkb"
    set -- "${@}" "-noxrecord"
    #set -- "${@}" "-noxfixes"
    set -- "${@}" "-noxdamage"
    set -- "${@}" "-display" "${DISPLAY}"
    set -- "${@}" "-forever"
    set -- "${@}" "-bg"
    set -- "${@}" "-rfbauth" "${TMOE_X11_PASSWD_FILE}"
    set -- "${@}" "-users" "$(whoami)"
    set -- "${@}" "-rfbport" "${TCP_PORT_FOR_RFB_PROTOCOL}"
    set -- "${@}" "-noshm"
    set -- "${@}" "-desktop" "tmoe-linux"
    set -- "${@}" "-shared"
    set -- "${@}" "-verbose"
    set -- "${@}" "-cursor" "arrow"
    set -- "${@}" "-arrow" "${X11VNC_CURSOR_ARROW}"
    set -- "${@}" "-nothreads"
    set -- "x11vnc" "${@}"
    exec "$@" &
}
###################
tmoe_x11vnc_preconfigure() {
    if [ ! -e "${TMOE_X11_PASSWD_FILE}" ]; then
        x11vncpasswd
    fi

    if [ -e "${TMOE_LOCALE_FILE}" ]; then
        TMOE_LANG=$(cat ${TMOE_LOCALE_FILE} | head -n 1)
        export LANG="${TMOE_LANG}"
    else
        export LANG="zh_CN.UTF-8"
    fi
}
#################
source_tmoe_dbus_daemon() {
    . ${TMOE_TOOL_DIR}/gui/launch_dbus_daemon
}
###########
start_tmoe_xvfb() {
    unset "${@}"
    set -- "${@}" "${DISPLAY}"
    set -- "${@}" "-screen" "0" "${TMOE_X11_RESOLUTION}x24"
    set -- "${@}" "-ac"
    set -- "${@}" "+extension" "GLX"
    set -- "${@}" "+render"
    set -- "${@}" "-deferglyphs" "16"
    set -- "${@}" "-br"
    set -- "${@}" "-wm"
    set -- "${@}" "-retro"
    set -- "${@}" "-noreset"
    set -- "Xvfb" "${@}"
    exec "$@" &
}
####################
if [ "$(uname -r | cut -d '-' -f 3 | head -n 1)" = "Microsoft" ] || [ "$(uname -r | cut -d '-' -f 2 | head -n 1)" = "microsoft" ]; then
    start_windows_10_pulse_audio_server
fi
###############
start_x_session() {
    . ${XSESSION_FILE} &
}
#############
tmoe_x11vnc_preconfigure
source_tmoe_dbus_daemon
start_tmoe_xvfb
start_x_session
start_tmoe_x11vnc
###########
sleep 2s
echo "正在启动x11vnc服务,本机默认vnc地址localhost:5901"
echo "本机IPv6 vnc地址[::]:5900或::"
TMOE_IP_ADDR=$(ip -4 -br -c a | awk '{print $NF}' | cut -d '/' -f 1 | grep -v '127.0.0.1' | sed "s@\$@:5901@")
cat <<-EOF
The LAN VNC address 局域网地址${TMOE_IP_ADDR}
EOF
echo "您可能会经历长达10多秒的黑屏"
echo "You may experience a black screen for up to 10 seconds."
echo "您之后可以输startx11vnc启动，输stopvnc停止"
echo "You can type startx11vnc to start x11vnc,type stopvnc to stop it."
