#!/usr/bin/env bash
#################
export PULSE_SERVER=${PULSE_SERVER:-127.0.0.1}

unset WAYLAND_DISPLAY
export DISPLAY=:233

TCP_PORT_FOR_RFB_PROTOCOL=5902

TMOE_X11_RESOLUTION=1440x720

VNC_LOCALHOST=false

AUTO_START_DBUS=true
#################
# RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
PURPLE=$(printf '\033[35m')
# CYAN=$(printf '\033[36m')
RESET=$(printf '\033[m')
# BOLD=$(printf '\033[1m')
printf "${GREEN}%s ${YELLOW}%s${RESET} %s\n" "Starting" "x11vnc server" "..."
printf "%s\n" "The current ${BLUE}x11vnc port${RESET} is ${YELLOW}${TCP_PORT_FOR_RFB_PROTOCOL}${RESET}, and x11vnc address is ${GREEN}localhost${YELLOW}:${TCP_PORT_FOR_RFB_PROTOCOL}${RESET}"
stopvnc -no-stop-dbus 2>/dev/null
TMOE_X11_PASSWD_FILE=${HOME}/.vnc/x11passwd
X11VNC_CURSOR_ARROW=2
TMOE_LINUX_DIR='/usr/local/etc/tmoe-linux'
TMOE_LOCALE_FILE="${TMOE_LINUX_DIR}/locale.txt"
TMOE_GIT_DIR="${TMOE_LINUX_DIR}/git"
TMOE_TOOL_DIR="${TMOE_GIT_DIR}/share/old-version/tools"
XSESSION_FILE='/etc/X11/xinit/Xsession'
TIGERVNC_CONFIG_FILE='/etc/tigervnc/vncserver-config-tmoe'
TIGERVNC_VIEWER_WIN10='/mnt/c/Users/Public/Downloads/tigervnc/vncviewer64.exe'
[[ -n ${XDG_RUNTIME_DIR} ]] || export XDG_RUNTIME_DIR=/tmp/runtime-${UID}
[[ -e ${XDG_RUNTIME_DIR} ]] || mkdir -pv ${XDG_RUNTIME_DIR}
unset TMOE_WSL
#################
start_windows_10_pulse_audio_server() {
    . ${TMOE_LINUX_DIR}/wsl_pulse_audio
}
#################
start_win10_tigervnc() {
    case ${TMOE_WSL} in
    true)
        cd "${HOME}" || exit 1
        nohup ${TIGERVNC_VIEWER_WIN10} -PasswordFile "${TMOE_X11_PASSWD_FILE}" localhost:${TCP_PORT_FOR_RFB_PROTOCOL} &>/dev/null &
        cd - &>/dev/null || exit 1
        ;;
    esac
}
#####################
start_tmoe_x11vnc() {
    [[ ! -e ${TIGERVNC_CONFIG_FILE} ]] || . ${TIGERVNC_CONFIG_FILE} 2>/dev/null
    if [[ ${VNC_LOCALHOST} = true ]]; then
        set -- "${@}" "-localhost"
    fi
    set -- "${@}" "-ncache_cr"
    set -- "${@}" "-xkb"
    set -- "${@}" "-noxrecord"
    #set -- "${@}" "-noxfixes"
    set -- "${@}" "-noxdamage"
    set -- "${@}" "-display" "${DISPLAY}"
    set -- "${@}" "-forever"
    set -- "${@}" "-bg"
    set -- "${@}" "-rfbauth" "${TMOE_X11_PASSWD_FILE}"
    set -- "${@}" "-users" "$(whoami)"
    set -- "${@}" "-rfbport" "${TCP_PORT_FOR_RFB_PROTOCOL}"
    set -- "${@}" "-noshm"
    set -- "${@}" "-desktop" "${desktop}"
    set -- "${@}" "-shared"
    set -- "${@}" "-verbose"
    set -- "${@}" "-cursor" "arrow"
    set -- "${@}" "-arrow" "${X11VNC_CURSOR_ARROW}"
    set -- "${@}" "-nothreads"
    set -- "x11vnc" "${@}"
    "${@}" &
    start_win10_tigervnc
}
###################
tmoe_x11vnc_preconfigure() {
    [[ -s "${TMOE_X11_PASSWD_FILE}" ]] || x11vncpasswd
    if [ -e "${TMOE_LOCALE_FILE}" ]; then
        TMOE_LANG=$(head -n 1 ${TMOE_LOCALE_FILE})
    else
        case ${LANG} in
        *UTF-8) TMOE_LANG=${LANG} ;;
        *) TMOE_LANG="en_US.UTF-8" ;;
        esac
    fi
    export LANG="${TMOE_LANG}"
}
#################
source_tmoe_dbus_daemon() {
    if [[ ${AUTO_START_DBUS} = true ]]; then
        source ${TMOE_TOOL_DIR}/gui/launch_dbus_daemon
    fi
}
###########
start_tmoe_xvfb() {
    set -- "${@}" "${DISPLAY}"
    set -- "${@}" "-screen" "0" "${TMOE_X11_RESOLUTION}x24"
    set -- "${@}" "-ac"
    set -- "${@}" "+extension" "GLX"
    set -- "${@}" "+render"
    set -- "${@}" "-deferglyphs" "16"
    set -- "${@}" "-br"
    # WhenMapped default backing-store
    # set -- "${@}" "-wm"
    set -- "${@}" "-retro"
    set -- "${@}" "-noreset"
    set -- "Xvfb" "${@}"
    "${@}" &
}
####################
check_wsl() {
    if [[ -r /proc/version ]]; then
        UNAME="$(head -n 1 /proc/version)"
        case "${UNAME}" in
        *Microsoft* | *microsoft*)
            TMOE_CHROOT=true
            TMOE_WSL=true
            export TMOE_CHROOT TMOE_WSL
            start_windows_10_pulse_audio_server
            ;;
        esac
    fi
}
# if [ "$(uname -r | cut -d '-' -f 3)" = "Microsoft" ] || [ "$(uname -r | cut -d '-' -f 2)" = "microsoft" ]
###############
start_x_session() {
    bash ${XSESSION_FILE} &
}
#############
check_wsl
tmoe_x11vnc_preconfigure
source_tmoe_dbus_daemon
start_tmoe_xvfb
start_x_session
start_tmoe_x11vnc
###########
sleep 2s
TMOE_IP_ADDR=$(ip -4 -br -c a | awk '{print $NF}' | cut -d '/' -f 1 | grep -v '127\.0\.0\.1' | sed "s@\$@:${TCP_PORT_FOR_RFB_PROTOCOL}@")
case ${TMOE_LANG} in
zh_*UTF-8)
    cat <<-ENFOFX11VNCTIPS
正在启动x11vnc服务,本机默认vnc地址localhost:${TCP_PORT_FOR_RFB_PROTOCOL}
本机IPv6 vnc地址[::]:5900或::
The LAN VNC address 局域网地址${TMOE_IP_ADDR}
您可能会经历长达10多秒的黑屏
You may experience a black screen for up to 10 seconds.
您之后可以输startx11vnc启动，输stopvnc停止
You can type startx11vnc to start x11vnc,type stopvnc to stop it.
ENFOFX11VNCTIPS
    ;;
*)
    cat <<-EOF
Staring x11vnc server...
The ${YELLOW}local${RESET} x11vnc address is ${BLUE}localhost${GREEN}:${TCP_PORT_FOR_RFB_PROTOCOL}${RESET}
The ${YELLOW}LAN${RESET} x11vnc address is ${TMOE_IP_ADDR}
You may experience a black screen for up to 10 seconds.
You can type startx11vnc to start x11vnc,type stopvnc to stop it.
EOF
    ;;
esac
