#!/usr/bin/env bash
cat >${TMOE_STARTUP_SCRIPT} <<-ENDOFPROOT
	#!/usr/bin/env bash
	##################
	PROOT_USER="root"
	# You can specify a user. Default is root
	# 您可以指定用户，例如root或ubuntu，默认为root
	# Sie können einen Benutzer angeben

	HOME_DIR="default"
	# If the value is "default", the home directory will be auto-detected. You can enter an absolute path, for example, "/root".

	WORK_DIR="default"
	# Set the initial working directory to path. Some programs expect to be launched from a given directory but do not perform  any  chdir  by  them‐selves.  This option avoids the need for running a shell and then entering the directory manually.
	# 启动容器后进入的目录，默认为用户的主目录。请注意: 若您的默认登录shell为bash/zsh, 则请在“环境变量与登录项管理”处修改entrypoint。 
	################
	PROOT_BIN="default"
	# Optional value: "default", "system", "termux", "32", "prefix", or an absolute path.
	# You can specify the path where the binary file of proot is located. If the vaule is "default", it will use the default path of the system.
	# If the vaule is "32", it will use proot 32bit-version. If your host is arm64, and you want to run an i386/armhf container, then you can modify it to "32".
	# You can also enter an absolute path, for example, "\${PREFIX}/bin/proot"
	# 您可以自行编译proot,并指定其二进制文件所在路径。当此变量值为"default"时，将使用系统默认proot二进制文件所在路径；当其为"termux"时，将使用 "\${PREFIX}/bin/proot"。 
	# 您也可以输入完整路径,例如"/usr/local/bin/proot"
	# 请注意：若您使用了termux, 宿主机为64位(arm64)，容器为32位(i386/armhf)，则请使用32位版proot。如果arm64 termux使用了armhf版的proot，那么qemu-user-i386(arm64)也要切换为32位armhf版本。
	# if (host = arm64-android && container = i386) { armhf proot + qemu-user-i386(armhf) } 
	# else if (host = arm64-android && container = amd64) { arm64 proot + qemu-user-x86_64(arm64) } 
	# else if ( host = arm64 && container = arm64) { arm64 proot }

	PROOT_32_TERMUX_BIN="${TMOE_LINUX_DIR}/lib32/data/data/com.termux/files/usr/bin/proot"
	# PROOT_32_DEBIAN_BIN="${TMOE_LINUX_DIR}/lib32/usr/bin/proot"

	PROOT_LIBEXEC_LOADER="default"
	PROOT_32_TERMUX_LOADER="${TMOE_LINUX_DIR}/lib32/data/data/com.termux/files/usr/libexec/proot/loader"

	LD_LIB_PATH="default"
	PROOT_32_TERMUX_LD_LIB_PATH="${TMOE_LINUX_DIR}/lib32/data/data/com.termux/files/usr/lib"
	################
	KILL_ON_EXIT=true
	# Kill all processes on command exit. When the executed command leaves orphean or detached processes around, proot waits until all processes possibly terminate. This option forces the immediate termination of all tracee processes when the main command exits. Default is true.
	# 退出容器时, 自动杀掉所有进程, 默认为true

	PROOT_SYSVIPC=true
	# Handles System V IPC syscalls (shmget, semget, msgget, etc.) syscalls inside proot. IPC is handled inside proot and launching 2 proot instances will lead to 2 different IPC Namespaces. Default is true.

	PROOT_L=true
	# Correct the size returned from lstat for symbolic links. Default is true.

	PROOT_H=false
	# Hide files and directories starting with '.proot.'. Default is false.

	PROOT_P=true
	# Modify bindings to protected ports to use a higher port number. Default is true.

	FAKE_KERNEL=false
	# 伪造内核版本信息, 默认为false, 若将此变量值修改为true, 则启用该功能
	# Default is false.
	KERNEL_RELEASE="5.10.0-6-cloud-${ARCH_TYPE}"
	# Make current kernel appear as kernel release *string*.

	LINK_TO_SYMLINK=true
	# Replace hard links with symlinks, pretending they are really hardlinks. Emulates hard links with symbolic links when SELinux policies do not allow hard links. Default is true.

	# export PROOT_NO_SECCOMP=1

	PROOT_DEBUG=false
	# proot调试输出, 默认为false
	# Default is false.
	VERBOSE_LEVEL=2
	# Set the level of debug information to *value*. The higher the integer value is, the more detailed debug information is printed to the standard error stream. A negative value makes PRoot quiet except on fatal errors.

	OLD_ANDROID_VERSION_COMPATIBILITY_MODE=false
	# Default is false.
	# 旧系统/旧版本兼容模式
	# Set the values of PROOT_L, PROOT_H, PROOT_P and PROOT_SYSVIPC to false, and set FAKE_KERNEL to true.
	################
	#qemu

	HOST_DISTRO="${LINUX_DISTRO}"

	HOST_ARCH="${TRUE_ARCH_TYPE}"
	# Host architecture

	CONTAINER_ARCH="${ARCH_TYPE}"
	# 容器架构
	# Optional vaule: "amd64", "i386", "arm64", "armhf", "armel", "mipsel", "mips64el", "ppc64el", "s390x", "riscv64"

	QEMU_ARCH="default"
	# Optional vaule: "default", "X86-64", "i386", "aarch64", "aarch64_be", "arm", "armeb", "mipsel", "mips64el", "s390x", "riscv64"

	SKIP_QEMU_DETECTION=false
	# After skipping, qemu will be called forcibly.
	# 跳过qemu版本和架构的检测，并强制调用qemu。如需启用本选项，则请手动修改 QEMU_ARCH 的值为指定架构。

	QEMU_USER_STATIC=true
	# 当该值为true时，使用静态编译的版本。
	# If the value is false, please install qemu-user manually, for example, apt install qemu-user-i386 qemu-user-x86_64 qemu-user-aarch64 qemu-user-arm

	QEMU_32_ENABLED=false
	# If your host is arm64-android, and you are using 32bit proot, then enable qemu32.

	QEMU_USER_STATIC_PATH="${TMOE_LINUX_DIR}/lib/usr/bin"
	QEMU_USER_STATIC_32_PATH="${TMOE_LINUX_DIR}/lib32/usr/bin"

	QEMU_USER_BIN="default"
	# 默认会自动根据宿主机架构和容器架构来判断需要调用的qemu版本, 您可以指定特定版本的qemu二进制文件。
	# You can enter an absolute path, for example, "\${PREFIX}/bin/qemu-user-x86_64"
	################
	LOAD_ENV_FILE=true
	# Load the environment variable file when starting the container. Default is true.
	CONTAINER_ENV_FILE="${DEBIAN_CHROOT}/usr/local/etc/tmoe-linux/environment/container.env"

	LOAD_PROOT_CONF=false
	# Default is false.
	# 默认为false。当该值为true时，当前配置信息将会被配置文件里的内容所覆盖。
	PROOT_CONF_FILE="${CONFIG_FOLDER}/proot_global.conf"
	################
	DEFAULT_LOGIN_SHELL_01=zsh
	# The default login shell is zsh.
	# 默认登录shell是zsh
	# Die Standard-Login-Shell ist zsh.

	DEFAULT_LOGIN_SHELL_02=fish
	DEFAULT_LOGIN_SHELL_03=bash
	DEFAULT_LOGIN_SHELL_04=ash
	DEFAULT_LOGIN_SHELL_05=su
	# The lower the number, the higher the priority.
	################
	#mounts

	MOUNT_SD=true
	SD_DIR_01="/storage/self/primary"
	SD_DIR_02="/sdcard"
	SD_DIR_03="/storage/emulated/0"
	SD_DIR_04="\${HOME}/sd"
	SD_DIR_05="\${HOME}/Downloads"
	SD_DIR_06="\${HOME}/Download"
	SD_MOUNT_POINT="/root/sd"
	# The lower the number, the higher the priority. The highest priority directory will be mounted to the mount point.
	# 挂载sd，默认为true，SD_DIR为宿主机sd目录，SD_MOUNT_POINT为容器内的挂载点。优先级别高，且存在相应目录时，才会被挂载。默认挂载点为容器内部的"/root/sd"

	MOUNT_TERMUX=true
	TERMUX_DIR="/data/data/com.termux/files"
	TERMUX_MOUNT_POINT="/root/termux"

	MOUNT_TF=true
	TF_CARD_LINK="\${HOME}/storage/external-1"
	TF_MOUNT_POINT="/root/tf"
	# The value of TF_CARD_LINK is a symbolic link file.
	# TF_CARD_LINK的值为一个软链接文件

	MOUNT_STORAGE=true
	STORAGE_DIR='/storage'
	# If the value of "MOUNT_STORAGE" is "false", the relevant directory will not be mounted. Default is true.

	MOUNT_GITSTATUS=true
	GITSTATUS_DIR="${CONFIG_FOLDER}/gitstatus"
	GITSTATUS_MOUNT_POINT="/root/.cache/gitstatus"

	MOUNT_TMP=false
	TMP_SOURCE_DIR="${TMPDIR}"
	TMP_MOUNT_POINT="/tmp"

	#---
	NUM_OF_MOUNTS=12
	# uint8
	# 默认为12, 若您将该值修改为15, 则请手动添加MOUNT_SOURCE_13,MOUNT_SOURCE_14,MOUNT_SOURCE_15,MOUNT_POINT_13,MOUNT_POINT_14 & MOUNT_POINT_15 变量。
	# If you want to mount hundreds of directories, then you need to add variables manually.
	#---
	# MOUNT_SOURCE_1为第一个挂载源，MOUNT_POINT_1 为第一个挂载点，MOUNT_SOURCE_2为第二个挂载源 ...
	# 举个例子，假如您想将/storage/emulated/0/Download目录挂载至容器内部的/media/down, 那么MOUNT_SOURCE_1的值为"/storage/emulated/0/Download", MOUNT_POINT_1的值为"/media/down"
	# For example, if you want to mount the /storage/emulated/0/DCIM directory to /media/pic, then the value of MOUNT_SOURCE_2 is "/storage/emulated/0/DCIM", and the value of MOUNT_POINT_2 is "/media/pic"

	MOUNT_SOURCE_1=""
	MOUNT_POINT_1=""
	#---
	MOUNT_SOURCE_2=""
	MOUNT_POINT_2=""
	#---
	MOUNT_SOURCE_3=""
	MOUNT_POINT_3=""
	#---
	MOUNT_SOURCE_4=""
	MOUNT_POINT_4=""
	#---
	MOUNT_SOURCE_5=""
	MOUNT_POINT_5=""
	#---
	MOUNT_SOURCE_6=""
	MOUNT_POINT_6=""
	#---
	MOUNT_SOURCE_7=""
	MOUNT_POINT_7=""
	#---
	MOUNT_SOURCE_8=""
	MOUNT_POINT_8=""
	#---
	MOUNT_SOURCE_9=""
	MOUNT_POINT_9=""
	#---
	MOUNT_SOURCE_10=""
	MOUNT_POINT_10=""
	#---
	MOUNT_SOURCE_11=""
	MOUNT_POINT_11=""
	#---
	MOUNT_SOURCE_12=""
	MOUNT_POINT_12="" 
	#---

	MOUNT_SYSTEM=true
	SYSTEM_DIR="/system"

	MOUNT_APEX=true
	APEX_DIR="/apex"

	MOUNT_SYS=false
	SYS_DIR="/sys"

	MOUNT_DEV=true
	DEV_DIR="/dev"
	MOUNT_SHM_TO_TMP=true
	MOUNT_URANDOM_TO_RANDOM=true
	MOUNT_DEV_FD=true
	MOUNT_DEV_STDIN=true
	MOUNT_DEV_STDOUT=true
	MOUNT_DEV_STDERR=true
	MOUNT_DEV_TTY=true

	MOUNT_PROC=true
	PROC_DIR="/proc"
	FAKE_PROOT_PROC=true
	# Default is true.
	################
	TMOE_LOCALE_FILE="${CONFIG_FOLDER}/locale.txt"
	DEFAULT_SHELL_CONF="${CONFIG_FOLDER}/default_shell.conf"
	PROC_FD_PATH="/proc/self/fd"
	HOST_NAME_FILE="${DEBIAN_CHROOT}/etc/hostname"
	################
	main() {
	    case "\$1" in
	    i* | -i* | -I*)
	        tmoe t
	        exit 0
	        ;;
	    -vnc* | vnc*) startx11vnc ;;
	    -n | novnc*) novnc ;;
	    -x) startxsdl ;;
	    *) start_tmoe_gnu_linux_container ;;
	    esac
	}
	check_qemu_arch() {
	    TMOE_QEMU=true
	    case "\${CONTAINER_ARCH}" in
	    i386)
	        case \${HOST_ARCH} in
	        amd64 | i386) TMOE_QEMU=false ;;
	        *) TMOE_QEMU_ARCH="i386" ;;
	        esac
	        ;;
	    amd64) TMOE_QEMU_ARCH="x86_64" ;;
	    arm64) TMOE_QEMU_ARCH="aarch64" ;;
	    armhf)
	        case \${HOST_ARCH} in
	        arm64 | armhf) TMOE_QEMU=false ;;
	        *) TMOE_QEMU_ARCH="arm" ;;
	        esac
	        ;;
	    armel)
	        case \${HOST_ARCH} in
	        arm64 | armhf | armel) TMOE_QEMU=false ;;
	        *) TMOE_QEMU_ARCH="armeb" ;;
	        esac
	        ;;
	    ppc64el) TMOE_QEMU_ARCH="ppc64le" ;;
	    s390x) TMOE_QEMU_ARCH="s390x" ;;
	    mipsel) TMOE_QEMU_ARCH="mipsel" ;;
	    mips64el) TMOE_QEMU_ARCH="mips64el" ;;
	    riscv64) TMOE_QEMU_ARCH="riscv64" ;;
	    esac
	}
	check_qemu32_path() {
	    case \${QEMU_32_ENABLED} in
	    true) QEMU_PATH="\${QEMU_USER_STATIC_32_PATH}/" ;;
	    false) QEMU_PATH="\${QEMU_USER_STATIC_PATH}/" ;;
	    esac
	    [[ -e \${QEMU_PATH} ]] || unset QEMU_PATH
	}
	check_qemu_bin() {
	    case \${QEMU_USER_BIN} in
	    default | "")
	        case \${QEMU_USER_STATIC} in
	        true) QEMU_BIN="\${QEMU_PATH}qemu-\${TMOE_QEMU_ARCH}-static" ;;
	        false) QEMU_BIN="qemu-\${TMOE_QEMU_ARCH}" ;;
	        esac
	        ;;
	    *) QEMU_BIN="\${QEMU_USER_BIN}" ;;
	    esac
	}
	##############
	start_tmoe_gnu_linux_container() {
	    if [[ \${LOAD_PROOT_CONF} = true && -r \${PROOT_CONF_FILE} ]]; then
	        source \${PROOT_CONF_FILE}
	    fi
	    unset LD_PRELOAD PROOT_UID PROOT_GID PROOT_HOME CONTAINER_BIN_PATH
	    ############
	    case \${PROOT_USER} in
	    "" | root) ;;
	    *)
	        PROOT_UID=\$(grep "^\${PROOT_USER}:" ${DEBIAN_CHROOT}/etc/passwd | awk -F ':' '{print \$3}')
	        PROOT_GID=\$(grep "^\${PROOT_USER}:" ${DEBIAN_CHROOT}/etc/passwd | awk -F ':' '{print \$4}')
	    esac
	    if [[ -z \${PROOT_UID} ]]; then
	        PROOT_UID=0
	        PROOT_GID=0
	    fi
	    
	    case \${HOME_DIR} in
	    default | "")
	        case \${PROOT_USER} in
	        root | "") PROOT_HOME="/root" ;;
	        *)
	            PROOT_HOME=\$(grep "^\${PROOT_USER}:" ${DEBIAN_CHROOT}/etc/passwd | awk -F ':' '{print \$6}')
	            [[ -n \${PROOT_HOME} ]] || PROOT_HOME="/home/\${PROOT_USER}"
	            ;;
	        esac
	        ;;
	    *) PROOT_HOME="\${HOME_DIR}" ;;
	    esac

	    if [[ \${PROOT_USER} = root || -z \${PROOT_USER} ]]; then
	        set -- "\${@}" "--root-id"
	    else
	        set -- "\${@}" "--change-id=\${PROOT_UID}:\${PROOT_GID}"
	    fi

	    if [[ \${WORK_DIR} = default || -z \${WORK_DIR} ]];then
	        set -- "\${@}" "--pwd=\${PROOT_HOME}"
	    else
	        set -- "\${@}" "--pwd=\${WORK_DIR}"
	    fi
	    set -- "\${@}" "--rootfs=${DEBIAN_CHROOT}"
	    if [[ "\${HOST_DISTRO}" = 'Android' ]]; then
	        if [[ \${MOUNT_SYSTEM} = true ]]; then
	            if [[ -e "\${SYSTEM_DIR}" ]]; then
	                set -- "\${@}" "--mount=\${SYSTEM_DIR}"
	            fi
	        fi
	        if [[ \${MOUNT_APEX} = true ]]; then
	            if [[ -e "\${APEX_DIR}" ]]; then
	                set -- "\${@}" "--mount=\${APEX_DIR}"
	            fi
	        fi
	        if [[ \${KILL_ON_EXIT} = true ]]; then
	            set -- "\${@}" "--kill-on-exit"
	        fi
	        if [[ \${MOUNT_TF} = true ]]; then
	            if [[ -L "\${TF_CARD_LINK}" ]]; then
	                TRUE_TF_CARD=\$(readlink \${TF_CARD_LINK})
	                if [[ -e "\${TRUE_TF_CARD}" ]]; then
	                    set -- "\${@}" "--mount=\${TRUE_TF_CARD}:\${TF_MOUNT_POINT}"
	                fi
	            fi
	        fi
	        if [[ \${MOUNT_STORAGE} = true ]]; then
	            if [[ -e "\${STORAGE_DIR}" ]]; then
	                set -- "\${@}" "--mount=\${STORAGE_DIR}"
	            fi
	        fi
	        if [[ \${MOUNT_TERMUX} = true ]]; then
	            if [[ -e "\${TERMUX_DIR}/home" ]]; then
	                set -- "\${@}" "--mount=\${TERMUX_DIR}:\${TERMUX_MOUNT_POINT}"
	            fi
	        fi
	        if [[ \${OLD_ANDROID_VERSION_COMPATIBILITY_MODE} = true ]];then
	            PROOT_H=false && PROOT_L=false && PROOT_P=false && PROOT_SYSVIPC=false && FAKE_KERNEL=true
	        fi
	        [[ \${PROOT_SYSVIPC} != true ]] || set -- "\${@}" "--sysvipc"
	        [[ \${PROOT_L} != true ]] || set -- "\${@}" "-L"
	        [[ \${PROOT_H} != true ]] || set -- "\${@}" "-H"
	        [[ \${PROOT_P} != true ]] || set -- "\${@}" "-p"
	        [[ \${LINK_TO_SYMLINK} != true ]] || set -- "\${@}" "--link2symlink"
	    fi
	    ############
	    [[ \${FAKE_KERNEL} != true ]] || set -- "\${@}" "--kernel-release=\${KERNEL_RELEASE}"
	    [[ \${PROOT_DEBUG} != true ]] || set -- "\${@}" "--verbose=\${VERBOSE_LEVEL}"  
	    if [[ \${MOUNT_PROC} = true ]]; then
	        set -- "\${@}" "--mount=\${PROC_DIR}"
	    fi
	    if [[ \${MOUNT_DEV} = true ]]; then
	        set -- "\${@}" "--mount=\${DEV_DIR}"
	        [[ \${MOUNT_SHM_TO_TMP} != true ]] || set -- "\${@}" "--mount=${DEBIAN_CHROOT}/tmp:/dev/shm"
	        [[ \${MOUNT_URANDOM_TO_RANDOM} != true ]] || set -- "\${@}" "--mount=\${DEV_DIR}/urandom:/dev/random"
	        [[ \${MOUNT_DEV_FD} != true ]] || set -- "\${@}" "--mount=\${PROC_FD_PATH}:/dev/fd"
	        [[ \${MOUNT_DEV_STDIN} != true ]] || set -- "\${@}" "--mount=\${PROC_FD_PATH}/0:/dev/stdin"
	        [[ \${MOUNT_DEV_STDOUT} != true ]] || set -- "\${@}" "--mount=\${PROC_FD_PATH}/1:/dev/stdout"
	        [[ \${MOUNT_DEV_STDERR} != true ]] || set -- "\${@}" "--mount=\${PROC_FD_PATH}/2:/dev/stderr"
	        [[ \${MOUNT_DEV_TTY} != true ]] || set -- "\${@}" "--mount=\${DEV_DIR}/null:/dev/tty0"
	    fi

	    if [[ \${MOUNT_SYS} = true ]]; then
	        if [[ -e "\${SYS_DIR}" ]]; then
	            set -- "\${@}" "--mount=\${SYS_DIR}"
	        fi
	    fi

	    if [[ \${MOUNT_TMP} = true ]]; then
	        if [[ -e "\${TMP_SOURCE_DIR}" ]]; then
	            set -- "\${@}" "--mount=\${TMP_SOURCE_DIR}:\${TMP_MOUNT_POINT}"
	        fi
	    fi

	    if [[ \${MOUNT_GITSTATUS} = true ]]; then
	        if [[ -e "\${GITSTATUS_DIR}" ]]; then
	            set -- "\${@}" "--mount=\${GITSTATUS_DIR}:\${GITSTATUS_MOUNT_POINT}"
	        fi
	    fi
	    #############
	    unset QEMU_BIN
	    case \${SKIP_QEMU_DETECTION} in
	    true)
	        TMOE_QEMU=true
	        case \${QEMU_ARCH} in
	        default | "")
	            printf "%s\n" "ERROR, please modify the value of QEMU_ARCH in the configuration file."
	            TMOE_QEMU=false
	            ;;
	        *)
	            TMOE_QEMU_ARCH="\${QEMU_ARCH}"
	            check_qemu32_path
	            check_qemu_bin
	            ;;
	        esac
	        ;;
	    *)
	        case "\${CONTAINER_ARCH}" in
	        "\${HOST_ARCH}") TMOE_QEMU=false ;;
	        *)
	            check_qemu_arch
	            check_qemu32_path
	            check_qemu_bin
	            ;;
	        esac
	        ;;
	    esac
	    if [[ \${TMOE_QEMU} = true && -n \${QEMU_BIN} ]]; then
	        set -- "\${@}" "--qemu=\${QEMU_BIN}"
	    fi
	    #############
	    if [[ \${MOUNT_SD} = true ]]; then
	        for i in "\${SD_DIR_01}" "\${SD_DIR_02}" "\${SD_DIR_03}" "\${SD_DIR_04}" "\${SD_DIR_05}" "\${SD_DIR_06}"; do
	            if [[ -e \${i} ]]; then
	                set -- "\${@}" "--mount=\${i}:\${SD_MOUNT_POINT}"
	                break
	            fi
	        done
	    fi
	    for ((i = 1; i <= \${NUM_OF_MOUNTS}; i++)); do
	        MOUNT_SOURCE="MOUNT_SOURCE_\${i}"
	        MOUNT_POINT="MOUNT_POINT_\${i}"
	        if [[ -n \${!MOUNT_SOURCE} && -x \${!MOUNT_SOURCE} ]]; then
	            set -- "\${@}" "--mount=\${!MOUNT_SOURCE}:\${!MOUNT_POINT}"
	        fi
	    done
	    #######################
	    #The files in the /proc directory will be automatically detected during installation. If your host does not have permission to read them, there is no " #" before set.
	    #不同系统对文件权限的限制可能有所区别，以下文件在安装时会自动检测，仅当宿主机无权读取时，才会去除set前的注释符号。
	    if [[ "\${FAKE_PROOT_PROC}" = 'true' ]]; then
	        ##test01#set -- "\${@}" "--mount=${TMOE_PROC_PREFIX}.stat:/proc/stat"
	        ##test02#set -- "\${@}" "--mount=${TMOE_PROC_PREFIX}.version:/proc/version"
	        if [[ -e "${TMOE_PROC_PATH}/uptime" ]]; then
	            printf "%s" ""
	            ##test04#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/bus:/proc/bus"
	            ##buddyinfo#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/buddyinfo:/proc/buddyinfo"
	            ##cgroups#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/cgroups:/proc/cgroups"
	            ##consoles#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/consoles:/proc/consoles"
	            ##crypto#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/crypto:/proc/crypto"
	            ##devices#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/devices:/proc/devices"
	            ##diskstats#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/diskstats:/proc/diskstats"
	            ##execdomains#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/execdomains:/proc/execdomains"
	            ##fb#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/fb:/proc/fb"
	            ##filesystems#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/filesystems:/proc/filesystems"
	            ##interrupts#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/interrupts:/proc/interrupts"
	            ##iomem#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/iomem:/proc/iomem"
	            ##ioports#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/ioports:/proc/ioports"
	            ##kallsyms#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/kallsyms:/proc/kallsyms"
	            ##keys#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/keys:/proc/keys"
	            ##key-users#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/key-users:/proc/key-users"
	            ##kmsg#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/kmsg:/proc/kmsg"
	            ##kpageflags#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/kpageflags:/proc/kpageflags"
	            ##loadavg#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/loadavg:/proc/loadavg"
	            ##locks#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/locks:/proc/locks"
	            ##misc#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/misc:/proc/misc"
	            ##modules#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/modules:/proc/modules"
	            ##pagetypeinfo#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/pagetypeinfo:/proc/pagetypeinfo"
	            ##partitions#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/partitions:/proc/partitions"
	            ##sched_debug#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/sched_debug:/proc/sched_debug"
	            ##softirqs#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/softirqs:/proc/softirqs"
	            ##timer_list#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/timer_list:/proc/timer_list"
	            ##uptime#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/uptime:/proc/uptime"
	            ##vmallocinfo#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/vmallocinfo:/proc/vmallocinfo"
	            ##vmstat#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/vmstat:/proc/vmstat"
	            ##zoneinfo#set -- "\${@}" "--mount=${TMOE_PROC_PATH}/zoneinfo:/proc/zoneinfo"
	        fi
	    fi
	    ###################
	    #SET ENV
	    HOST_NAME="localhost"
	    if [[ -r \${HOST_NAME_FILE} ]]; then
	        HOST_NAME=\$(sed -n p \${HOST_NAME_FILE})
	    else
	        [[ ! \$(command -v hostname) ]] || HOST_NAME=\$(hostname -f)
	    fi
	    set -- "\${@}" "/usr/bin/env" "-i"
	    set -- "\${@}" "HOSTNAME=\${HOST_NAME}"
	    set -- "\${@}" "HOME=\${PROOT_HOME}"
	    set -- "\${@}" "TERM=xterm-256color"
	    set -- "\${@}" "SDL_IM_MODULE=fcitx"
	    set -- "\${@}" "XMODIFIERS=\@im=fcitx"
	    set -- "\${@}" "QT_IM_MODULE=fcitx"
	    set -- "\${@}" "GTK_IM_MODULE=fcitx"
	    set -- "\${@}" "TMOE_CHROOT=false"
	    set -- "\${@}" "TMOE_PROOT=true"
	    set -- "\${@}" "TMPDIR=/tmp"
	    set -- "\${@}" "DISPLAY=:0.0"
	    set -- "\${@}" "PULSE_SERVER=tcp:127.0.0.1:4713"
	    if [[ -r "\${TMOE_LOCALE_FILE}" ]]; then
	        set -- "\${@}" "LANG=\$(head -n 1 \${TMOE_LOCALE_FILE})"
	    else
	        set -- "\${@}" "LANG=en_US.UTF-8"
	    fi
	    #SHELL
	    [[ ! -r \${DEFAULT_SHELL_CONF} ]] || source \${DEFAULT_SHELL_CONF}
	    if [[ -z \${TMOE_SHELL} ]]; then
	        for i in \${DEFAULT_LOGIN_SHELL_01} \${DEFAULT_LOGIN_SHELL_02} \${DEFAULT_LOGIN_SHELL_03} \${DEFAULT_LOGIN_SHELL_04} \${DEFAULT_LOGIN_SHELL_05}; do
	            if [[ -f ${DEBIAN_CHROOT}/bin/\${i} || -L ${DEBIAN_CHROOT}/bin/\${i} ]]; then
	                TMOE_SHELL="/bin/\${i}"
	                break
	            fi
	        done
	    fi
	    set -- "\${@}" "SHELL=\${TMOE_SHELL}"
	    #LOAD GLOBAL ENV FILE
	    if [[ -s \${CONTAINER_ENV_FILE} && \${LOAD_ENV_FILE} = true ]]; then
	        CONTAINER_BIN_PATH=\$(sed -E 's@export\s+@@;/#/d' \${CONTAINER_ENV_FILE} | grep '^PATH=\"' | grep '\${PATH:+:\${PATH}}' | sed 's@\${PATH:+:\${PATH}}\"@:@;s@PATH=\"@@')
	        OLD_IFS="\${IFS}"
	        IFS=\$'\n'
	        CONTAINER_ENV_VAR="\$(sed -E 's@export\s+@@;/#/d;/^PATH=/d' \${CONTAINER_ENV_FILE})"
	        # Do not use double quotes in CONTAINER_ENV_VAR in the for statement
	        for i in \${CONTAINER_ENV_VAR}; do
	            [[ -z \${i} ]] || set -- "\${@}" "\${i}"
	        done
	        IFS="\${OLD_IFS}"
	    fi
	    #PATH ENV
	    if [[ \${PROOT_USER} = root || -z \${PROOT_USER} ]]; then
	        set -- "\${@}" "PATH=\${CONTAINER_BIN_PATH}/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games"
	    else
	        set -- "\${@}" "PATH=\${CONTAINER_BIN_PATH}/usr/local/bin:/bin:/usr/bin:/usr/games:/usr/local/games"
	    fi
	    #LOGIN SHELL
	    #It should be -l, not --login
	    set -- "\${@}" "\${TMOE_SHELL}" "-l"
	    ###################
	    unset PROOT_LOADER LD_LIBRARY_PATH
	    case "\${PROOT_BIN}" in
	    "" | system | default) PROOT_PROGRAM=proot ;;
	    termux | prefix) PROOT_PROGRAM="\${PREFIX}/bin/proot" ;;
	    32)
	        case \${HOST_DISTRO} in
	        Android)
	            PROOT_PROGRAM="\${PROOT_32_TERMUX_BIN}"
	            PROOT_LOADER="\${PROOT_32_TERMUX_LOADER}"
	            LD_LIBRARY_PATH="\${PROOT_32_TERMUX_LD_LIB_PATH}"
	            ;;
	        *) PROOT_PROGRAM=proot ;;
	        esac
	        ;;
	    *) PROOT_PROGRAM="\${PROOT_BIN}" ;;
	    esac
	    set -- "\${PROOT_PROGRAM}" "\${@}"
	    case \${PROOT_LOADER} in
	    "")
	        case "\${PROOT_LIBEXEC_LOADER}" in
	        default | system | "") ;;
	        *) PROOT_LOADER="\${PROOT_LIBEXEC_LOADER}" ;;
	        esac
	        ;;
	    esac
	    case "\${LD_LIBRARY_PATH}" in
	    "")
	        case "\${LD_LIB_PATH}" in
	        default | system | "") ;;
	        *) LD_LIBRARY_PATH="\${LD_LIB_PATH}" ;;
	        esac
	        ;;
	    esac
	    if [[ -n \${PROOT_LOADER} && -z \${LD_LIBRARY_PATH} ]]; then
	        set -- "env" "PROOT_LOADER=\${PROOT_LOADER}" "\${@}"
	    elif [[ -z \${PROOT_LOADER} && -n \${LD_LIBRARY_PATH} ]]; then
	        set -- "env" "LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}" "\${@}"
	    else
	        set -- "PROOT_LOADER=\${PROOT_LOADER}" "\${@}"
	        set -- "env" "LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}" "\${@}"
	    fi
	    exec "\${@}"
	}
	main "\${@}"
ENDOFPROOT

#TMOE_LINUX_DIR & TRUE_ARCH_TYPE & ARCH_TYPE + $.

case $(uname -o) in
Android) ${TMOE_CHROOT_PREFIX} termux-fix-shebang ${TMOE_STARTUP_SCRIPT} ;;
esac
chmod a+rx ${TMOE_STARTUP_SCRIPT}
ln -sf ${TMOE_SHARE_DIR}/container/debian/debian ${PREFIX}/bin
# 64 | tmoe)
#     case \${HOST_DISTRO} in
#     Android)
#         PROOT_64_TMOE_BIN="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/bin/proot"
#         PROOT_64_TMOE_LOADER="${TMOE_LINUX_DIR}/lib/data/data/com.termux/files/usr/libexec/proot/loader"
#         PROOT_PROGRAM="\${PROOT_64_TMOE_BIN}"
#         PROOT_LOADER="\${PROOT_64_TMOE_LOADER}"
#         ;;
